import Link from "next/link";
import About from "./about/page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/home">Home</Link>
              {/* <a href="/">Home</a> */}
            </li>
            <li>
              {/* <a href="/reviews">Reviews</a> */}
              <Link href="/reviews">Reviews</Link>
            </li>
            <li>
              {/* <a href="/about">About</a> */}
              {/* <Link href="/about">About</Link> */}
              <Link href="/animals/dogs">Dogs</Link>
            </li>
          </ul>
        </nav>
        <header style={{ border: "solid blue 1px" }}>[Main Header]</header>
        <main>{children}</main>
        <footer style={{ border: "solid blue 1px" }}>[Main Footer]</footer>
      </body>
    </html>
  );
}
