export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
  };
   
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>
          <nav>
            <ul>
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/reviews">Reviews</a>
              </li>
              <li>
                <a href="/about">About</a>
              </li>
            </ul>
          </nav>
          <header style={{ border: "solid blue 1px" }}>[Main Header]</header>
          <main>{children}</main>
          <footer style={{ border: "solid blue 1px" }}>[Main Footer]</footer>
        </body>
      </html>
    );
  }